package cn.edu.hzvtc.entity;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acc.id
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acc.username
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acc.password
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_acc.role
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    private String role;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acc.id
     *
     * @return the value of tbl_acc.id
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acc.id
     *
     * @param id the value for tbl_acc.id
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acc.username
     *
     * @return the value of tbl_acc.username
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acc.username
     *
     * @param username the value for tbl_acc.username
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acc.password
     *
     * @return the value of tbl_acc.password
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acc.password
     *
     * @param password the value for tbl_acc.password
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_acc.role
     *
     * @return the value of tbl_acc.role
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_acc.role
     *
     * @param role the value for tbl_acc.role
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    public Account() {
    }

    public Account(Integer id, String username, String password, String role) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.role = role;
    }

    public Account(String username, String password) {
        this.username = username;
        this.password = password;
    }

    @Override
    public String toString() {
        return "Account{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", role='" + role + '\'' +
                '}';
    }
}