package cn.edu.hzvtc.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import javax.validation.constraints.Email;
import javax.validation.constraints.Pattern;
import java.util.Date;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.id
     *
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_name
     *
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    @Pattern(regexp = "(^[a-zA-Z0-9_-]{6,16}$)|(^[\\u2E80-\\u9FFF]{2,5}$)",
            message = "用户名错误")
    private String empName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_gender
     *
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    private String empGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_birthday
     *
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date empBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_email
     *
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    @Email
    private String empEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_salary
     *
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    private Float empSalary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.create_time
     *
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    @JsonFormat(pattern = "yyyy-MM-dd")
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.dept_id
     *
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    private Integer deptId;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.id
     *
     * @return the value of tbl_emp.id
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.id
     *
     * @param id the value for tbl_emp.id
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_name
     *
     * @return the value of tbl_emp.emp_name
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_name
     *
     * @param empName the value for tbl_emp.emp_name
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_gender
     *
     * @return the value of tbl_emp.emp_gender
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public String getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_gender
     *
     * @param empGender the value for tbl_emp.emp_gender
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public void setEmpGender(String empGender) {
        this.empGender = empGender == null ? null : empGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_birthday
     *
     * @return the value of tbl_emp.emp_birthday
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public Date getEmpBirthday() {
        return empBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_birthday
     *
     * @param empBirthday the value for tbl_emp.emp_birthday
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public void setEmpBirthday(Date empBirthday) {
        this.empBirthday = empBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_email
     *
     * @return the value of tbl_emp.emp_email
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_email
     *
     * @param empEmail the value for tbl_emp.emp_email
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail == null ? null : empEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_salary
     *
     * @return the value of tbl_emp.emp_salary
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public Float getEmpSalary() {
        return empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_salary
     *
     * @param empSalary the value for tbl_emp.emp_salary
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public void setEmpSalary(Float empSalary) {
        this.empSalary = empSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.create_time
     *
     * @return the value of tbl_emp.create_time
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.create_time
     *
     * @param createTime the value for tbl_emp.create_time
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.dept_id
     *
     * @return the value of tbl_emp.dept_id
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.dept_id
     *
     * @param deptId the value for tbl_emp.dept_id
     * @mbg.generated Mon May 25 18:08:25 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }


    private Department department;

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    public Employee() {
    }

    public Employee(Integer id, String empName, String empGender, Date empBirthday, String empEmail, Float empSalary, Date createTime, Integer deptId) {
        this.id = id;
        this.empName = empName;
        this.empGender = empGender;
        this.empBirthday = empBirthday;
        this.empEmail = empEmail;
        this.empSalary = empSalary;
        this.createTime = createTime;
        this.deptId = deptId;
    }

    public Employee(Integer id, String empName, String empGender, Date empBirthday, String empEmail, Float empSalary, Integer deptId) {
        this.id = id;
        this.empName = empName;
        this.empGender = empGender;
        this.empBirthday = empBirthday;
        this.empEmail = empEmail;
        this.empSalary = empSalary;
        this.deptId = deptId;
    }

    public Employee(Integer id, String empName, String empGender, String empEmail, Integer deptId) {
        this.id = id;
        this.empName = empName;
        this.empGender = empGender;
        this.empEmail = empEmail;
        this.deptId = deptId;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "id=" + id +
                ", empName='" + empName + '\'' +
                ", empGender='" + empGender + '\'' +
                ", empBirthday=" + empBirthday +
                ", empEmail='" + empEmail + '\'' +
                ", empSalary=" + empSalary +
                ", createTime=" + createTime +
                ", deptId=" + deptId +
                ", department=" + department +
                '}';
    }
}