package cn.edu.hzvtc.dao;

import cn.edu.hzvtc.entity.Account;
import java.util.List;

public interface AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    int insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_acc
     *
     * @mbg.generated Wed May 27 23:24:07 CST 2020
     */
    int updateByPrimaryKey(Account record);


    String selectPwdByName(String username);

    String checkName(String username);
}